---
title: |
  "Statistical Analysis of Immunoglobin Isotype Fingerprints Across Afflictions " 
  \newline
  "Statistisk Analyse af immunoglobin Isotype Fingeraftryk for Forskellige Sygdome"
author: |
  "Jakob Gad Spoorendonk"
  "Bachelors Thesis"
date: 2026-05-05
header-includes:
  - \supervisors{Veit Stefan Schwämmle\protect\\ Xuan-Tung Trinh}
bibliography: references.bib
csl: ./styles/nature.csl
execute:
  echo: true
  warning: false
format:
  pdf:
    pdf-engine: xelatex
    #cite-method: biblatex
    toc: true
    toc-depth: 2
    toc-float: false
    toc-title: "Table of Contents"
    include-in-header:
      - text: |
          \usepackage{tikz}
          \usetikzlibrary{positioning, chains}
          \usepackage{graphicx}
          \graphicspath{{Pictures/}}

          \usepackage{fontspec}
          \setmainfont{TeX Gyre Termes}
          \setsansfont{TeX Gyre Heros}
          % \setmonofont{Consolas}

          \usepackage{sectsty}
          \allsectionsfont{\bfseries}
          \sectionfont{\Huge\centering}
          \subsectionfont{\LARGE\centering}
          \subsubsectionfont{\Large\centering}
      - file: preamble.tex
---
\newpage

# Abstract
Antibodies play a vital role in the adaptive immune system. They are highly adaptive in terms of role due to their flexible structure. Antibodies can change their function by altering their isotype, and they can change what activates them by changing the variable region. Antibodies are produced by B cells. B cells are activated by antigen-presenting cells that present antigens from pathogens to the B cells. Different pathogens trigger the production of different isotypes of antibodies, and these different isotypes fulfil different roles by activating different parts of the immune system. This should be observable in proteomics data from older experiments. In order to use old data it is necessary to know the parameters that were used for data acquisition. This is normally not well documented on PRIDE where the data is hosted.

# Resume
Antistoffer spiller en vigtig rolle i det adaptive immunesystem. De er meget adaptive på grund af deres fleksible opbygning. Antistoffer kan ændre deres funktion ved at skifte isotype, og de kan skifte hvad der aktiverer dem ved at ændre deres variable region. Antistoffer bliver produceres af B celler. B celler bliver aktiveres af antigen presenterende celler der presenterer antigener fra patogener til B cellerne. Forskellige patogener vil frembringe produktionen af forskellige isotyper af antistoffer, og disse forskellige isotyper udfylder forskellige roller ved at aktivere forskellige delle af immun systemet. Dette burde være muligt at se i proteomics data fra ældre eksperimenter. For at bruge ældre data er det nødvendigt at kende de parametre der var brugt til dataindsamlingen. De er desværre normalt ikke godt dokumenteret på PRIDE hvor dataene findes. 

# Hypothesis
The working hypothesis is that: If someone has a certain type of disease then the antibody fingerprint will not change. The independent variable will be the disease or the disease type, and the dependent variable will be the antibody fingerprint. The null hypothesis is $h_0 = h_1$ with the alternative hypothesis being $h_0 \notequal h_1$ with an $\alpha = 0.05$. One-way ANOVA was used due to it being a comparison between groups. If ANOVA returns a significance value less than the a value post-hoc tests will be considered and performed. The fasta file used was uniprots human genome file of Proteome ID: UP000005640.fas with a 50% decoy rate, which makes it 20464 decoys out of 40928 proteins. The FDR for the dataset was set to 1%.

## Limitations of study
Due to a low number of studies with available data the results will not be very conclusive. With only a single category of diseases (Viral) it is impossible to extrapolate the result to other types of disease and their potential impact on the antibody fingerprint.


# Introduction

## Humoral Immune Response
Humoral immunity is part of the adaptive immune system and it is mainly mediated by the presence of antibodies. There are two main types of humoral immunity: T-dependent and T-independent. T-independent immunity is triggered by the presence of an antigen that is recognized by the B cell receptor (BCR), but not by T helper cells. This leads to a humoral immune response dominated by IgM antibodies. T-dependent immunity occurs when a B cell is able to internalize the antigen and present it to a T helper cell on the B cell's major histocompatability complex (MHC), allowing the B cell to undergo class-switch recombination to generate antibodies of different isotypes . 

### Antibodies  
Antibodies are produced and secreted by B cells. They are proteins that form part of the adaptive immune system. They play a central role in humoral immunity by attaching to recognized targets to trigger various reactions. All human antibodies consist of two identical light chains and two identical heavy chains. Both chains contain a variable region. The light chain contains a single conserved region, while the heavy chain contains either four (IgM and IgE) or three (the rest) conserved regions. This depends on the antibody isotype. Between the first conserved region, which is connected to the variable region, and the second conserved region is a hinge region. Depending on the isotype, the hinge region can be longer or shorter, thereby controlling the flexibility of the antibody arms . The different isotypes can interact with different immune receptors, referred to as Fc receptors.

The two arms of the antibody are referred to as fragment antigen binding domains (Fabs), and the bottom connecting part is referred to as the fragment crystallizable (Fc). The variable regions of both Fabs are identical, as they are made from the same light- and heavy-chain combination. The hinge region is found between these two parts. 



#### Variable Region
The variable region of an antibody comprises the N-terminal region of the light and heavy chains . This is the part of the antibody that binds to an antigen and contributes to activation of immune effector mechanisms . The variability is generated through several mechanisms, allowing the body to produce antibodies that can rapidly become specific to a wide range of antigens that may appear. 

#### Hinge Region
Between the Fabs and Fc is the hinge region. The different isotypes and subtypes have different hinge regions. The hinge region of an antibody is found between the first and second constant regions of the heavy chain. 
The hinge region can be subdivided into three regions: upper hinge, core hinge, and lower hinge. Each of the three regions plays a different role. The upper hinge determines the flexibility and rotational capacity of the Fabs. The core region contains a varying number of cysteine residues, which differs between subtypes. These cysteines are used to stabilize and connect the heavy chains. The lower hinge region is used to bend the Fc region of the antibody which affects the orientation of the Fc region, relative to the antigen-binding arms . The length and disulfide bonds of the hinge region affect the flexibility and reach of the variable region. They also affect Fc receptor binding affinity and downstream effector functions .


#### Constant Region
The main part of antibodies is made up of constant regions, which are stable, unlike the variable region. The light chain has a single constant region which is attached to a constant region of the heavy chain to hold them together. The constant region of the heavy chain is what determines the isotype of the antibody. The isotype of the antibody determines which effector function the antibody will trigger when binding to a target antigen . The function of an antibody is dependent on which effector functions it triggers. The Fc region determines receptor-binding specificity, thereby determining which immune receptors the antibody can cross-link with. Because the Fc region consists of the conserved part of the heavy chain, it determines which receptors an antibody can interact with and therefore which reactions it can trigger. The antibodies and their respective receptors function together to initiate downstream immune responses . 


## Variability
Antibodies are very variable proteins in terms of sequence. This variability can be seen in the variable region which can be adapted to consistently react only to very specific patterns. It is also reflected in the constant region which can be swapped out to mediate a completely different response previously. B cells produce this variability through several highly regulated mechanisms and processes inside the cell. 

#### V(D)J Recombination
The variability of the variable region partially comes from V(D)J recombination. V(D)J recombination is different between the variable regions in the heavy chain and light chain. On the heavy chain it involves all three segments: the V (variable), D (diverse), and J (joining) segments, whereas the light chain only has the V and J segments. By combining multiple different V and J segments it is possible to generate several different variable-region combinations which can subsequently undergo mutation . By combining these basic forms with mutations introduced through SHM it is possible for the immune system to reach a high degree of sequence diversity for affinity maturation to improve upon.

#### Activation-induced cytidine deaminase (AID)
One of the key enzymes in generating variability in antibodies is activation-induced cytidine deaminase (AID). It is a protein that plays a vital role in the adaptive immune system. It is used in the variability-generating processes of CSR and SHM which ultimately leads to double-stranded DNA breaks. The main mechanism of AID is the controlled deamination of cysteine in the variable region of the antibodies. This turns the cysteine into a uracil, which should not be in the DNA. When uracil is detected in DNA it triggers a double-stranded break in the DNA which is then repaired, replacing uracil with cystein, as it originally was . 
AID contributes indirectly to the DNA changing between repair events. When a break is induced in DNA it is normally repaired with very high precision. During a breakage caused by AID the normal DNA repair pathways are suppressed, which causes the cell to use less reliable DNE repair mechanism. These less than ideal means cause the DNA to be imperfectly repaired, leading to mutations in the variable region where AID activity occurs. By inducing mutations in this region of the DNA it increases the diversity of variable regions in this B cell lineage . 

##### Somatic Hypermutation (SHM)
Mutations happen to the variable region in B cells over the span of few generations. Somatic hyper mutation is how the B cell performs random insertion, deletion, and base substitution between generations. It mainly occurs in the variable region of the DNA where the AID is supposed to be acting. This causes a buildup of minor changes in the DNA encoding the variable region, thereby increasing the number of potential combinations that can be created . B cells carrying higher affinity mutations are selected for further mitosis, this causes the next generation of antibody producing B cells to produce antibodies of higher affinity .

##### Affinity Maturation
These higher affinity B cells are chosen through competition. The overall process is referred to as Affinity Maturation. Affinity maturation is one of the main mechanisms of the adaptive immune system's adaptation to diseases. It uses SHM to rapidly generate a diverse range of variable regions, and then select the best ones for further production and adaptations. B cells that have been activated, cycle between two zones: the dark zone (DZ) and the light zone (LZ). In the light zone B cells compete for the interactions with T follicular helper cells, which select the highest affinity cells, to enter the dark zone to proliferate. Inside the dark zone B cells divide and SHM triggers more mutations, most of these mutations will have a negative impact on the affinity of the B cell. After a few rounds of replication, the B cells are then pushed out of the dark zone into the light, to once again fight for the right to enter the dark zone for replication . While the affinity maturation cycle is running, the B cells are also exposed to environmental factors like cytokines that can induce class switching in them.

##### Class Switch Recombination (CSR) 
When certain criteria are met the B cell will edit its own DNA and switch from one isotype to another. Class switching is a one-way process. Class switch recombination is the process by which B cells change the constant region of the heavy chain of the antibodies they produce. This is done by splicing different parts of the DNA together, excising the intervening DNA. This makes it impossible for the transformation to be reversed, as the DNA is not there. Even though there is no mutation during CSR, AID is necessary to trigger the double-strand breaks to excise the DNA before recombining the DNA. The excision points are predefined by switch regions in the DNA. These regions are used as target points for the DNA break to ensure that the DNA cleavage is clean and that resulting heavy chains remain functional . With the excision of only some DNA it allows the downstream B cell generations to undergo further class-switch recombination events for further adaptation . Which DNA is excised depends on which cytokines are present at the time of activation, which determines the isotype that the B cell will change to. 

#### Fc Glycosylation 
Post-translational modifications (PTMs) play an important role in the function and behaviour of proteins. Different isotypes have different patterns for post-translational modifications. It is one of the things that differentiate the functions of the different antibody isotypes. By switching isotype the potential modifications available for the antibody also change. Additionally, due to a positional change the same type of PTM can now have a different effect on the interactions of the antibody.

Potential modifications include glycosylation, which is of special importance to the function of antibodies. Glycosylation is the attachment of an oligosaccharide molecule to an amino acid. It can occur in two overarching forms: O-glycosylation where the oligosaccharide is attached to the oxygen atom of the hydroxyl group of a serine or threonine and N-glycosylation where it is attached to the nitrogen atom of an asparagine side chain. There are several types of glycosylation, named after the oligosaccharide used. These different oligosaccharides have different effects on the function of the protein they are bound to. The oligosaccharide used has also been observed to vary from continent to continent, whether this is due to genetics, diet, or other circumstances is unknown. But it is known that glycosylation type can change with age, and that indicates that it is potentially a combination of several different factors . 

Glycosylation is one of the main differentiators in functionality between the isotypes, and their subtypes. The different isotypes have different amounts of asparagines that can accept N-glycosylation. Glycosylation and its effect on antibodies has mainly been studied for IgG antibodies. N-glycosylation of IgG Fc region mainly happens in the cells where the antibodies are produced. The glycosylation of Asn297 in IgG alters the configuration to an open state of the Fc domain. Antibodies are not the only part of the humoral immunity that is affected by glycosylation. Fc$\gamma$RIIIa has five N-glycosylation sites, the IgG Asn297 glycosylation site can interact with the Asn162 site of the immune receptor, to promote antibody receptor cross-linking. Glycosylation status is not a permanent thing, and it is not absolute. Only 12% of IgG3 are glycosylated on Asn392 which it alone amongst the IgGs possess. Glycosylation also directly affects the functionality of the antibodies themselves. Glycosylation in IgG has been linked to increased binding of antibodies to C1q, which activates the classical complement pathway . It plays a vital role in combating diseases and that has been noted by some pathogens.

Some diseases affect the body's ability to perform different glycosylations on certain antibodies. This generally occurs by lowering the amount of enzymes that are available to perform that specific type of glycosylation. This can have what appears to be a targeted effect on certain antibody isotypes. It is possible to use changes in IgG glycosylation of Asn297 to find out if someone has active or latent tuberculosis. Evolutionarily this is probably a survival mechanism of the pathogen. It also indicates that the glycosylation plays an active role in the function of the antibodies . With glycosylation being so important the differences between isotypes in terms of glycosylation is a part of the features that separate the different isotypes.

## Isotypes
Antibodies come in five main isotypes, some isotypes exist as several subtypes. The different isotypes differ structurally in various ways, not just in their length but also in their glycosylation and their cysteine placement. It is these structural differences that the body uses to selectively interact with the individual antibodies to mediate which immune response is triggered by which isotype . Although there are many different versions, at the root they are all produced to fulfil the same function. Recognise antigens and annihilate intruders. 


### IgM
IgM is the default isotype of mature B cells. It contains 4 conserved regions, and in the blood, they form pentamers. They are the best activators of the complement system. IgM can be produced without being exposed to antigenic stimuli, but they can also be produced against invading pathogens . It serves as the primary defence against early pathogen invasions, before adaptive immunity has been activated .  

Early Immune responses are generally characterised by a rise in antigen-specific IgM, which is then followed by affinity maturation, and then by isotype switching. This gives rise to antibodies that are specialised in combating that specific illness, thereby increasing the likelihood of survival for the host. IgM tends to have a lower antigen-binding affinity than the other isotypes, in nature, this is compensated for by being the isotype most strongly associated with responses against non-protein antigens . This is because in order to class-switch it is necessary for the B cell to react to an antigen that can be recognised by the MHC II receptor on the follicular T-cell, which can only recognize proteins. Clinically humans have overcome this by attaching proteins to molecules of interest, thereby allowing the Tfh cells to induce class switch on B cells that are not protein specific 

### IgD
IgD is the other type of immunoglobulin that is produced by naive B cells . It is believed to have arisen evolutionarily slightly after IgM, and is preserved from fish to humans. This kind of preservation would indicate that it is necessary for the survival of the organism. The maturation of B cells is characterized by progressive up-regulation of IgD based receptors. B cells that purely express IgD are anergic B cells and tend to exist in the peripheral regions of the body, but interestingly not in the intestine . This may be due to the presence of the intestinal microbiota, but if IgD were a danger to the commensal microbes a similar pattern would be expected for IgA antibodies, which are the main excretory antibodies.

IgD stands out amongst the isotypes for several reasons. One of the more noteworthy ones is that it can coexist with another isotype. This is because it is produced through alternative splicing of the same gene that produces IgM, but unlike other isotypes it has an individual gene to code for its heavy chain. Although it initially coexists with IgM, it is possible for B cells to class switch so that they only express IgD. The process of CSR to IgD appears to differ from normal CSR, which is another reason to think that IgD should be considered separate from the other isotypes . 

Because IgD is produced through alternative splicing of the IgM transcript there is an argument to be made that it should really be called IgM2 and be classified as a subtype of IgM. Some arguments against that would be the existence of an individual gene for its heavy chain  and unlike other subtypes, which appear to represent specialised functional variants, IgD fills a distinctive role in the immune system in terms of functions due to having independent receptor reactions from IgM . 


### IgG
IgG antibodies come in four subtypes, IgG1, IgG2, IgG3, and IgG4. These subtypes are numbered in order of decreasing abundance. All four subtypes can be produced by the G class B cells. The different subtypes have different affinity for different receptors of the Fcγ family. Through the different affinities they are able to fulfil different purposes in the immune system. With the exception of Fc$\gamma$RIIb, all of the Fc$\gamma$R receptors mediate activating functions .

#### IgG1
IgG1 is the body's response to soluble proteins and membrane proteins. They are the most abundant of the IgG antibodies, and are often encountered together with the other IgG subtypes, especially IgG3 and IgG4 . IgG1 is able to cross-link with all of the different Fc$\gamma$R receptors to activate them . 

#### IgG2
IgG's reaction to bacterial capsular polysaccharides is almost entirely made up of IgG2 antibodies . IgG2 mainly triggers receptors on neutrophils, it might also be able to trigger receptors on NK cells and some macrophages . This would lower the scope of the reaction, triggering only the necessary cells for fighting the bacterial infection. This may help restrict the immune response to the most relevant effector cells, which increases survivability.

#### IgG3
IgG3 is the antibody with the longest hinge domain, counting up to 62 amino acids in length. It also has the highest affinity for C1q which makes it the best IgG to trigger the complement system. It does have the shortest half-life amongst the long lived IgG's. Just like IgG1 it can interact with all of the Fc$\gamma$R .

#### IgG4
IgG4 is an antibody that is often formed following repeated non-infectious exposure. It is linked to downregulation of immune response towards the antigen and is usually seen correlating with successful immunotherapy . IgG4 has a couple of unique functions as compared to the other IgG subtypes. It doesn't have a C1q domain for triggering the complement system . It also has the ability to exchange half of its molecules with other IgG4 antibodies, which would allow one antibody to target two separate antigens for immune suppression .

### IgA
IgA is the most abundantly produced antibody isotype in the body, it is the second most prominent antibody in the blood. More IgA is produced in total than all the other isotypes combined. It is encountered in all mammals and birds. Most IgA is secreted out of the body, usually in the form of sIgA, which mainly forms dimers at mucosal surfaces, and sometimes they also form tetramers. IgA comes in two major subtypes, IgA1 and IgA2.  

There are several differences between the two subtypes. The two main differences between the two subtypes, are the length of their hinge regions and their glycosylation sites. The significantly longer hinge region of IgA1 makes the Fabs with the variable regions significantly more flexible, and increases their spatial reach reach. In the serum there is roughly a nine to one ratio of IgA1 to IgA2 while in the mucosal tissue the ratio is less lopsided. The two subtypes induce different signalling in some cells which is probably due to a combination of the hinges being different and the differing glycosylation patterns. The production of two different subtypes of IgA is something that is only found in the ape family from which humans evolved .

### IgE
IgE is the antibody type mainly associated with allergic and parasitic diseases. It mainly interacts with receptors on basophils, monocytes and macrophages, with some other immune cells carrying lower affinity receptors. When an antibody-receptor complex is triggered the triggered cells degranulate completely, this degranulation triggers high levels of inflammation and cascading reactions . The relatively high affinity of IgE receptors, as compared to other antibody-receptor complexes, drastically lowers the amount of IgE that is freely found in blood serum.  

IgE is the least abundant antibody in the blood. This is probably partially due to the shorter lifespan when unbound, which is 1.5 days , and the fact that it is produced in response to parasites, which are more rare than microorganisms. In some individuals IgE antibodies are produced as a response to harmless antigens, this failure can lead to the symptoms of allergy . One possible explanation for the growing prevalence of allergy is due to the lower variation in IgE leading to an increased amount of mast cells being triggered by a single harmless antigen.


### BCR
B cells don't just make antibodies for other cells to use, B cells themselves can use the antibodies to build a receptor. The B cell receptor is a membrane bound receptor that is constructed using antibodies. Immature B cells use IgM as the antibody for the BCR, but as they mature it is gradually replaced by IgD. All of the isotypes can be used for constructing BCRs. The isotype used is based on the class switch of the B cell. By using different isotypes it is possible for the B cells to have different reactions to the same receptor being triggered. An antibody that forms a part of the BCR is referred to as a membrane-bound immunoglobulin, or mIg for short. On the Fc end of the antibody is attached a transmembrane anchor section, which anchors the antibody through the membrane and acts as an intercellular signaling domain when the antibody is triggered. The effector is associated with CD79A and CD79B which each carry an immunoreceptor tyrosine-based activation motif (ITAM). These Motifs are what allows the BCR receptor to pass on the signal .

There are several theories about how the BCR receptor works, but it always seems to have some behaviour that defies the logic of the model. While the model may not have been established, the basic sequence of events is known. The process starts with a variable region of the BCR. It is either triggered by a soluble antigen fragment, or more likely, deliberately triggered by antigen presentation by follicular dendritic cells. The BCR activation triggers the ITAM part of CD79A and CD79B. The ITAMs then trigger a cascade of reactions that always lead to transcriptional changes in the B cell. Which transcriptional changes occur depends on the isotype used in the receptor .

## Effector Functions
 When a BCR or another antibody-associated receptor is triggered, a cascade of reactions termed effector functions follows. Antibodies have the ability to trigger two main types of effector function, either binding to receptors to trigger transcriptional change, or they activate the complement system. Which reaction occurs depends on the antibody isotype, depending on whether they possess a C1q domain and which Fc receptors they can bind to.

#### Complement System
The complement system is one of the basic defence mechanisms of the body. It consists of a series of proteins, that through a proteolytic cascade of reactions lead to opsonization, recruitment and membrane lysis. Complement activation is a three-phase process, initiation, activation and effector phases. The initiation phase of the complement system has three pathways, the classical, alternative, and lectin pathways. The classical pathway is initiated by antigen-antibody immune complexes. It is activated when an antibody with a C1q domain binds to something. The ability of an antibody to activate the classical pathway is directly related to the affinity of its C1q domains. This determines the ability of the antibody to bind complement proteins. For IgG the C1q affinity is ordered IgG3 > IgG1 > IgG4 > IgG2. As the complement cascade progresses, a part of the cleaved complement proteins have an inflammatory effect on the immune system. If the target isn't removed in other ways, the complement proteins form MAC, the Membrane Attack Complex which lyses the victim . As the complement cascade progresses, a part of the proteolysed complement proteins have an inflammatory effect on the immune system. As the cascade progresses, if the target hasn't been removed in other ways, the complement proteins come together to form MAC, the Membrane Attack Complex, which lyses the victim . The complement system plays a part in both innate and adaptive immunity, if the pathogens do not succumb to the hostile environment of the body, immune cells subsequently contribute to pathogen clearance. 

#### Immune Receptors
The body has several immune receptors that play different roles in the immune system. A subset of these receptors can interact with the Fc of antibodies to trigger various effector functions, such as opsonization, and transcriptional changes. If the antibody is attached to an immune receptor when it binds to an antigen it will trigger the immune receptor, and it is still possible for the immune receptor to be attached after the antibody has found its target to trigger it. There are several types of immune receptor, as it is a categorisation for all receptors involved in the immune system. A subset of these receptors work by binding to the Fc of antibodies to cause an effect, these are the Fc receptors. These Fc receptors help coordinate the humoral immune response through the usage of immunoreceptor tyrosine-based activation motif. The motifs are triggered when the receptor is cross-linked with an antibody. These receptors can trigger a wide variety of downstream effects, that can vary depending on the cell type expressing the receptor . The naming of immune receptors follows a simple convention, where Fc_R_ stands for "Fragment crystallizable _type_ Receptor _number_". An example is Fc$\gamma$RII, which is Immunoglobin G receptor type 2 . What reactions occurs depend on the isotype of the antibody, and that depends on which disease caused the class switch.

## Diseases of Interest
The ideal triggers of B-cell-related activity are pathogens. These pathogens will hopefully be recognized by the B cells and then become targets of a specific immune response with the help of affinity maturation and class switching. This will change the population distribution of antibodies based on the type of pathogen that is present. The transcriptional changes induced as a response to the disease will affect which effector functions are used against the pathogen. The different pathogens require different solutions, and the immune system reacts based on the identiy of the pathogen.

#### Viral 
One common type of pathogen is viruses. It is a non-living bundle of DNA protected by a coating, that hijacks the replicative machinery of a living organism to create more copies of itself. A common type of viral disease is viral respiratory infection. It is the most common category of infectious disease, and a leading cause of death worldwide. With a growing population and climate change the threat of viral diseases is increasing each year .

#### Bacterial 
Another common pathogen is bacteria. Bacteria have a long evolutionary history, and have therefore had plenty of time to adapt to various conditions. They occupy a broad variety of ecological niches, so it is not weird that there are some of them that have humans as their ecological niche .

A severe category of bacterial diseases is bloodstream infections. When bacteria start colonising the blood vessels and cause systematic damage to the body. These bacteria will rapidly colonize the blood vessels, while evading the immune system. In normal situations Bacteraemia will rapidly be cleared from the bloodstream by the immune system . 

#### Fungal
Fungal diseases are generally characterised by being slow to progress, and deadly if not treated. Mammals in general are far less susceptible to fungal diseases than other animals. This is probably because of the naturally high internal temperature of mammals, which greatly hinders the activity of the fungus, while being combined with the humoral immunity. The importance of the immune system can be seen in the high presence of fungal diseases in immunocompromised people . Fungi, unlike many other pathogens builds itself up as a structure when it is infectious, which exposes them to constant attacks from antibodies triggering membrane attack complexes (MACs). The constant attacks would puncture the fungal membranes and hinder its development.

#### Parasitic 
Parasites are organisms that live at the expense of their host. Parasites are divided into two categories, protists (single-celled organisms) and helminths (worms/metazoans). Helminths are large in relation to the size of the host cells, and most have evolved strategies to protect themselves from the immune system, or avoid being recognised by it . This size difference may contribute to the reaction of IgE being so extreme, and why so little IgE is produced. With an extreme reaction to kill the multicellular organism and the low amount to reduce inappropriate activation. Because there are two major types it stands to reason that the immune system has two distinct responses to parasites. One response for the protists, and one for the helminths.


#### Allergies
Allergies are an immune reactions to the presence of harmless particles. It is caused by the degranulation of mast cells which is considered a hallmark of allergy. The most studied trigger for degranulation of mast cells is the cross-linking of IgE-Fc$\epsilon$RI. Mast cells reside in tissue that is exposed to the external environment. They are therefore often amongst the first immune cells to encounter pathogens and respond to them. When triggered mast cells cause massive inflammation and recruit nearby immune cells to fight whatever it is that triggered them . The diversity of IgE may influence the proportion of mast cells that degranulate due to harmless antigens.

## Proteomics 
Theory says that different antibodies are produced against different disease. Proteomics can be used to test hypotheses in protein research. Proteomics is the study of a large number of proteins from the same source. It allows for the answering of questions in relation to the abundance, localisation, interactions, modification states, and folding of proteins. Proteomics is commonly divided into two main approaches, bottom-up and top-down. In bottom-up proteomics an overall picture of the protein abundance is created and then further studied in order to get an overview of the situation, and find out how the different proteins play together. Top-down proteomics  on the other hand makes it possible to analyse isoforms of the same proteins, but it becomes harder to gain a complete overview . There exist many tools for performing proteomics, but modern proteomics is mainly done on a mass spectrometer.

### Mass Spectrometry
Mass spectrometry is performed using a mass spectrometer. A mass spectrometer is a molecular weight that measures the mass-to-charge (m/z) ration of ions. A mass specrometer is made up of six components, an inlet system, an ion source, a mass analyser, a Detector, a vacuum system, and a recorder. Of these six components, three (ion source, mass analyser, and detector) can be varied for different types of analysis. These three components work together to first ionise the sample, sort it, and detect the molecular composition and concentration distribution of the sample.

A mass spectrometer starts with an ion source. The purpose of the ion source is to ionises the sample molecules. The ionised particles can then be converted from a non-gaseous phase to a gaseous phase so that they can be analysed by the mass analyser. There are several ways to ionise a molecule, and that has led to the creation of several different ion source instruments. Ionisation is split into hard ionisation and soft ionisation. Which to use depends again on the molecules that are being analysed. The categorization of hard and soft corresponds to high and low internal energy being transferred to the sample molecules during the ionization process. For biological samples with complex molecules, soft methods are preferable. They do not break the molecule in the process which would make the analysis unreliable . Currently the two main ion sources used in proteomics are "matrix-assisted laser desorption/ionization (MALDI)" and electrospray-ionisation, which are both soft methods.

The mass analyser is the part of the instrument that is used to affect the ions so that the detector can detect differences between them. The sample molecules are separated based on their mass to charge ratio. Mass analysers use several different methods to separate the ions based on their characteristics. Currently there are four main types of mass analyser in use, quadrupole, quadrupole ion trap, time of flight, and Fourier transform ion cyclotron resonance. The different mass analysers are used for different purposes based on several parameters such as resolution and price of usage. In order to analyze only particles within a certain m/z range several mass analysers can be put in sequence, this is referred to as tandem mass spectrometry .

After the mass separation a relevant mass detector is used to determine the mass of the ion based on how it has been inside the mass analyser. Mass detectors are analytical devices which detect the passing or arrival of ions and their absolute or relative concentration of each analyte in the sample. Over the history of mass spectrometry, there have been several different types of mass detector. Many of these mass detectors are used in conjuction with specific mass analysers. When a detector is triggered it outputs a signal, that after amplification is traced on a recorder .

#### Bottom-up Proteomics
There are two major categories of mass spectrometry in the field of proteomics, top-down proteomics (TDP), and bottom-up proteomics (BUP). Bottom-up proteomics is the analysis of enzymetically digested proteins . The goal of BUP is the efficient, consistent, and effective extraction and digestion of proteome samples for analysis. The general workflow of BUP is made up of; protein extraction, followed by hydrolysis, Reversed-phase liquid chromatography (RPLC), ionisation, and then finally mass spectrometry. Depending on circumstances, various changes can be made to this flow to fit whatever criteria that are necessary .


#### Top-down Proteomics
The major difference between BUP and TDP is whether the proteome of interest in pre-digested or not. The predigestion changes the difficulty of answering different questions. The digestion of proteins that is characteristic of BUP has the side effect of making it hard to analyse the post-translational modifications of the proteins, which are important for their functions. There are of course also challenges to using TDP, some of them are the need for both accurate intact molecular mass measurement(top) and controlled fragmentation during the gas-phase .



#### DDA Mass Spectrometry
Data-dependent acquisition (DDA) is a form of tandem mass spectrometry. It functions by selecting the most abundant precursor ions detected by MS1 survey then fragments and analyse them . One of the problems with DDA is that it has a bias towards stronger signals, that makes it harder to reproduce quantification of low-abundance peptides . One attempt to solve this issue was the usage of dynamic exclusion settings, which mitigates the problem to some extent. But this is an inherent flaw with DDA and has led to the creation of new techniques like DIA mass spectrometry .

#### DIA Mass Spectrometry
Data-independent acquisition (DIA) is the newer approach to data acquisition . It tries to solve the bias issue of DDA by using a different approach. DIA enables the isolation and fragmentation of all the acquired precursors, by cycling through predefined _m/z_ windows across a preset range . This eliminates the bias by making each precursor the largest in its cycle and therefore allowing the identical treatment for the different precursors regardless of abundance.

 
#### Labelling
When analysing samples it is important to know if and how the samples are labeled. Labeling samples makes it possible to run them together. This decreases the potential for technically induced bias caused by running the samples seperately. It does also add the extra step of labeling the samples, and if it isn't done correctly that can also affect the outcome of the experiment. Two types of labeling are; stable isotope labeling, and isobaric tag labeling .

Stable isotope labeling relies on feeding the sample with stable isotopes of the atoms it uses, generally carbon. This produces peptides that are chemically identical while having a slightly different mass . The obvious downside of this method is the labeling process itself, it works for microbes, but is probably impossible to perform at scale with anything larger. And the isotopes are expensive to produce and procure.

Isobaric tag labeling is another approach to running several samples at once. There are various methods of performing isobaric tag labeling. The basic approach is to attach a different isotopic mass tag to all of the molecules in a sample. These mass tags can then later be used to differentiate between the samples. The tags themselves are stable isotope reagents that can be attached to the peptides, and differ enough that it is possible to note the difference between them during analysis .


### Datasource 

#### PRIDE
PRIDE is the online protein repository of the European Molecular Biology Laboratory (EMBL). It stands for The PRoteomics IDEntifications Archive database, and is a public data repository for mass spectrometry data. The goal of PRIDE is to support the performance of reproducible research through the application of quality control metrics and enable the reuse of data for purposes other than the original study. The source of the datasets in this study is PRIDE and each dataset contains the ftp address from which it came . PRIDE has four major web interfaces: PRIDE archive, PRIDE Archive USI, the PRIDE Crosslinking resource, and PRIDE spectral libraries. These different resources fulfil different functions in the PRIDE ecosystem. PRIDE supports the FAIR (Findable, Accessible, Interoperable, Reusable) principles, and is constantly working towards the furtherance of these concepts in the database .

#### FragPipe
FragPipe is an application designed to be a comprehensive computational platform for the analysis of mass spectrometry proteomics data. It functions as a wrapper over several proteomics tools, such as MSFragger, IonQuant, DiaNN, and more. It provides a comprehensive list of workflows that combine the tools to turn multistep processes into a set-up-and-run workflow. The analysed data is generally turned into tables of quantified proteins, which are easy to work with for future analysis. FragPipe is developed and maintained by Nesvilab. it is open-source, and under continuous development. FragPipe documentation can be found at the url https://fragpipe.nesvilab.org/, which is made with github pages and is sourced from the https://github.com/Nesvilab/FragPipe.git github repo .

#### DIA-NN 
Data-independent acquisition Neural Network, is the main tool used by FragPipe to analyse DIA data. It uses deep neural networks to solve one of the largest issues with DIA mass spectrometry, the analysis of the data. As data is not acquired in one round, but rather through cycling it loses the context window that makes it easy to analyse the data. With no baseline DIA data is hard to analyse and peaks can be confused for several precursors at once, as there are several corresponding spectrums. The neural networks are used to distinguish real signals from noise, it combines those predictive capacities with new quantification and interference-correction methods at the time of its development .

When it starts it uses a selection of precursor ions to build a spectral library which is used as a foundation for future quantification of the peaks. It then generates a negative control library from the decoy precursor information, and uses that to identify potential peaks that should overlap between the decoy and the real data. After the preparatory work it then proceeds to evaluate every elution peak with a set of scores that describes the peaks characteristics, while comparing with the generated spectral library. It then evaluates the degree of interference between the precursors with similar retention time, and if the interference is significant enough to take into account. Then it keeps the ones that have the least interference, this has been found to increase the strict false discovery rate (FDR). One of the most important steps in the workflow is that it assigns statistical significance to the identified precursors, in the form of q-values. The q-values are calculated by assigning a discriminant score based on the potential characterisations of the elution peaks. The program then uses the trained neural network to distinguish between the decoys and the actual peaks. It then proceeds to select the most likely fragment based on the level of interference and best agreement with te spectral library .

#### SDRF-proteomics 
After data has been gathered and analysed, it is important to store it for future analysis. As increasing amounts of data is generated, it is becoming increasingly important to standardise the notation of this data. But which data is essential for understanding, and reproducing the experiment. There are two types of data that are important: the data that makes it possible to understand the experiment, metadata, and the data that describes the process and makes it possible to reanalyse the data. These are two separate goals, and need two separate solutions. The first is solved by using a meatadata file describing the dataset structure. The second is in the process of being solved in proteomics.

In metabolomics, they use the ISA-TAB format, and in transcriptomics the MAGE-TAB format is fulfilling a similar role. Proteomics has the SDRF format, which aims to achieve a similar purpose. Due to historical reasons it is not as widely adopted as the former two, it is also much younger than the other two and is therefore largely based on them. The goal is to create a format that will contain the necessary information to reproduce the data analysis. The general structure of the current version of this file splits the information into three groups, and pair them to cover the biological replicate * technical replicate characteristic of proteomics . It provides a foundation for reanalysis of data and cross-study comparison, enabeling new findings.





## This Study 
This project is a continuation of the study "Data mining antibody sequences for database searching in bottom-up proteomics" which was focused on the isotype distribution of B cells recorded in the Open Antibody Space. The original study was interested in the variable region of the antibody chains, with the goal of creating an antibody database to support the discovery of unregistered antibodies . Unlike the original, this study is focused on the distribution of the variation in the Fc part of the antibody.



# Method 

## Data Collection
Data was gathered from the PRIDE repository. The goal was to gather datasets of serum samples, from a wide range of disease conditions. Iterative dialog was performed with ChatGPT for datasets containing human serum samples from various disease, it forgot partway through the conversation that it was supposed to give serum samples, and it wasn't very thorough with the list it created. After having processed the datasets that the chatbot had found, another attempt was made with claude, which produced a python code for questioning the pride API, plus keywords. Finally a systematic query-based search was conducted, systematically going through all entries on pride that had organism "homo sapiens" and organism part as one of the following; "blood serum, blood, or blood plasma. The datasets with promising names were written down in a document which can be found in the project repository (GitHub:Trenchcoat-capybara/Antibody-fingerprints/tree/main/pride_repository/chat_databases.md).

The next step was to look through the article related to the datasets of interest to find the parameters to use for FragPipe analysis, and to see if there were any issues with the dataset in relation to the project itself. This aimed to remove the datasets where there were issue that made it useless for the study. The datasets where it was impossible to infer which dataset belonged to which group were discarded. As were the datasets where antibodies had been removed, and those that contained non-serum protein data.

## Data Analysis 
After the datasets were verified, the few remaining were run through FragPipe, using the appropriate workflow, which leans on the DIA-NN software. 

The chosen dataset (PXD036074) was decompressed with a dockerised version of proteowizard using the msconvert tool. The main tags of interest peakPicking and "zeroSamples removeExtra". They were then transfered to the compute instance "Ucloud" where they were analysed using 4 cores of with 6 GB of memory each. 

The complete Command used was "docker run -it --rm -v ./:/data proteowizard/pwiz-skyline-i-agree-to-the-vendor-licenses wine msconvert ./*.wiff --mzML --filter "peakPicking true 1-" --filter "zeroSamples removeExtra" -z -o ./result"


The decoded data files were analysed in fragpipe using the DIA_SpecLib_Quant with the following parameters. The enzyme was set to trypsin. The precursor size was 12 ppm and the fragmentation size to 20 ppm. The instrument was SCIEX 7600 ZenoTOF in the acquisition mode Zeno Swath MS (DIA). Fixed modifications included carbamidomethylation of cysteine, and variable modifications included oxidation-Met and N-term Acetyl. It came from the organism Homo Sapien. The data was created with a label free DIA workflow.

The spectral libraries were aggregated (using csvstack from csvkit) the different patients into a single csv. After that the aggregated csv was inserted into postgres by using the csvsql tool of csvkit. The files were then loaded using the DBI R package, using the file names to sort the data according to disease and disease type.

The main data of interest in the output was the PG.Normalised values and their pairing to different isotypes. The PG.Normalised is the normalised registered quantity for the protein group. Each patient had multiple entries per isotype, so each of the isotypes was summed into a single value for each isotype per patient. In order to prepare the data for visualization, and to make it comparable across samples, the values were turned into percentages. They were then turned into two sets of data, one with all of the subtypes, and one with the subtypes summed up to represent the distribution between isotypes only.


## Data Visualization and Statistics
Data visualization was performed with R using the ggplot2 package. The goal was originally to compare the distribution of isotypes across different disease categories, but data availability limited the analysis to two disease of the same category, plus control samples. First diseases were treated as independent groups for statistical analysis, and then based on disease type. ANOVA was used to compare across groups. 









# Results
## Distribution of the Data

I analysed the data from the study "The human host response to monkeypox infection: a proteomic case series study". 

The study contained 31 patients. @fig-isocount shows the number of patients for each disease, and the number of patients each isotype was recorded for.


There are more control samples than there are samples for either of the disease. The two diseases combined contain one more sample than the control pool. 

It is interesting to note, that there is not a single IgE entry. The only other isotype that isn't found in every patient is IgD. The lack of IgE can be explained by its nature, but what is the reason for the missing IgD.

IgE is the least produced antibody isotype. Furthermore, it is paired with the highest affinity receptor. 
The combination of these two factors may be the reason it isn't in any of the samples, even the DIA methodology has problems detecting very low quantities of proteins. Another factor could be the origin of the patients, they live in Britain. IgE is a response to parasites, sanitation improvements - like separation of drinking water and excretion - have probably lowered the average IgE levels in countries with good infrastructure.

IgD is mostly produced in the peripheries of the body, which would mean that none peripheral blood has lower levels of IgD. Considering that, the normal place to take blood from is the arm - which is far away from where IgD is produced - may have an effect on the IgD levels. 



As can be seen in @fig-dist, there is a very low amount of IgD in the samples, this could be why there are several patients that didn't register any IgD, it is below the measurable level. This would overlap with the plausible reason that IgE was not found.

Another thing of interest is the Covid IgG1. Based on the boxplot shape, there are 2 extreme outliers. This could be because there are only 10 samples in the study; it is possible that a whole section of the expected normal distribution is missing. 
It could be reasonable to pool the samples based on disease type. If so, then there would be no outliers in the IgG1 section, as the monkeypox entries would link the two Covid IgG1 clusters. This could be reasonable due to both diseases being very similar, and therefore probably trigger a similar immune reaction.


## Comparing Means across Diseases
In order to get a better understanding of the differences between the diseases and the control the means were calculated and plotted.
The main divergences in mean can be seen in IgG1 and IgG3. With these divergences being similar for the two viral diseases there is a good chance that they will interfere with each other if counted separately. This grouping is supported by the original study having chosen Covid do have something functionally similar to compare their monkeypox cases to. There is therefore good reason to compare across different diseases as well as different disease types.

The divergence of IgG1 and IgG3 make them the isotypes with the highest potential to be statistically significant. I will therefore focus on statistical analaysis for them going forward. As they are both IgG subtypes; The isotype subtypes will not be collapsed to just isotypes.

## Analysis of Groups 
If Covid and monkeypox are supposed to be treated as one group; it should be visible on a graph, In theory, if they were one group then the pooles samples should be normally distributed, with a shared mean. 

There appears to somekind of relationship, but there are too few samples to say from a graph. It is therefore necessary to perform some statistical tests to see if the two viral samples should be counted separately. The density graphs with control samples show two small bumps, this is another potential indicator that there are two factors here, Control and Viral. With the purely viral graphs only having one peak, it once more supports the pooling of viral samples.

## Statistical Comparison of Viral Diseases
There are a couple of statistical tests that can be used to detect the differences between two groups. The most basic one is the ANOVA test, which compares within group variation with between group variation.


While the table shows that the means of the respective IgG1 and IgG3 concentrations of Covid and monkeypox are closer to each other than either of them are to the control sample, it doesn't really tell us if these are the same sample group or different.



As can be seen from the graphs there is a very high chance that the two groups are really one. An interesting aspect to this is that the two outliers from IgG1 Covid dataset are suddenly no longer outliers, they slot in perfectly with the viral disease type category. While this is a potential explanation, the low amount of samples makes it is hard to use this to prove that they are the same group.

As it cannot be shown that the two belong to the same group, comparison of groups with anova was first performed using the disease name as differentiating factor. 


With a Pr(>F) of around 0.19 for both isotypes it would inidicate that having a covid or monkeypox has no significant effect on the isotype-fingerprint of a person. Based on the earlier graphs this makes less sense than the idea that the double count of viral infection is interfering.


By counting the viral infections as a single group the Pr(>F) falls to around 0.075 which is not below the general significance level of 0.05. With the low sample size there is an argument to be made that 0.075 is close enough to consider further research, but until otherwise proven it indicates that there is no correlation between disease type and antibody fingerprint.

# Discussion

## Database Sourcing with LLMs 
In order to speed up the process of dataset discovery LLMs were used. The two LLMs used were ChatGPT and Claude Sonnet. LLMs are supposed to be good at sorting through a lot of data. It was therefore assumed that it might be able to lessen the load of searching through the datasets in PRIDE and find the truely useful ones.

When ChatGPT was asked for datasets containig serum or blood samples for different diseases, it only gave a few even when asked for as many as possible. When asked for further datasets it seemed to 'forget' that the datasets had to be serum or blood samples. It was therefore necessary to check all of its work, which created more work than just finding the datasets in person as it proved to be unreliable.

Claude had a different approach, it said it couldn't access the PRIDE API and then produced a python script that could be used to access the API. The script wasn't completely thought through, as it was only able to do keyword search. This made it hard to specify it as only serum samples, and it was just easier to do a generalised keyword search using the PRIDE websites inbuilt search engine, even though it would be preferable to have AND/OR operators in that.


## Exhaustion of Proteins
One of the common issues with data on PRIDE was the lack of annotation about what the dataset contained, or didn't contain. There were a lot of datasets that had removed the 14 most common proteins in the blood. This was done to stop them from interfering with the analysis of other, less common, proteins. But that information was buried as a single line in the method section of the article, which was sometimes locked behind a paywall. If it was the first time that day this wasn't important, but when it was the umpteenth report that day it was becomming a real drag on the search.

It could be intersting to add some fields to the properties tab in the PRIDE archive or in other ways enforce the disclosure of such measures. The main idea would be to enforce the disclosure of modifications to the sample so that it can quickly be discountet if that modification that makes the dataset not work with the study. The inclusion of the modification should be as simple as possible, to not distract from the data upload itself.

## Annotation of Data
There was a severe lack of usable annotation of data on PRIDE. Several of the datasets were had files that were only differentiated by number, which makes the only way of knowing which are the control contacting the original makers of the data. It would appear that, to many getting the data onto PRIDE is an afterthought and no time has been put into thinking about what information needs to be included. This could be seen by the constant lack of things like the precursor size, and dataset labeling. It would be interesting if PRIDE added some datapoints that must be filled in to allow the datasets to be posted there. If they actually performed the experiment they should have notated the precursor size, fragmentation size, and other processing information somewhere and it would therefore be easy to make that available for others to redo the data analysis.

Once more it could be useful to have some more properties fields in the archive. It could be sub categories of the Experiment type, or software, the important part is to make it possible to reanalyse the data while lowering the amount of extra work that has to be done. The objective is once more to make it as painless as possible to reuse the data, thereby increasing the potential for future research. This was a non-exhaustive list of parameters, butthe same basic idea would be applicable here. These kinds of fields could also be enforced on an SDRF format.

Another project that could be of use, would be to have a team that goes through older datasets and with the help of the researchers create the SDRF files that are missing. These SDRF files would make the older datafiles that lack the information needed for reusability give the data new life.

## Statistical Testing 
Even though the reliability of the statistical testing is hindered by the low sample pool, there are results of potential interest. When initially treating the data the disease type was of secondary importance, and that led to results where the two viral vectors interfered with each other. With the visible difference in the values from statistical testing between using disease as factor versus using the disease vector type as the factor. The p-value differences between the two sample groupings indicate the importance of grouping for future experiments. 

While there was an intention to see if it was possible to use a random forest to find constant differences between different categories of disease. With the small sample size and disease type pool it makes no sense to fit a random forest on top of it.

## The Importance of subtypes
With the OAS being isotype distribution data based on genetic data. It raises the question, is it necessary to include the subtypes? It is easier to perform an analysis using the genome of extracted cells. This could be an incentive, but that would presume that every B cell is producing the same amount of antibodies, and the subtypes are not of major importance. There is a known difference between the active production of antibodies of different types of B cell. Different types of antibodies produce different amounts of antibodies. But even if that is accounted for there seems to be a need to take account of the subtype as well. As can be seen from the data in @fig-comppct the increase in IgG1 is similar to the decrease in IgG3, this difference would be lost when using genomics in order to record the change in isotype fingerprint.

It would also seem that there is no need to strictly classify the data entries according to individual diseases. This may be due to Covid and monkeypox being disease that are very similar in terms of function, which is why covid was used as a comparison marker to monkeypox in the original study. It could be interesting to see if this would hold up with other viral diseases that function in a different way. With the current data there is an indication that the main factor of importance for the change in isotype fingerprint is the disease vectors type. Although this is hard to conclude on as Covid and monkeypox were chosen because they are very similar in several aspects. 

## Sample Type
The samples being serum samples may skew the viewed isotype distributions. This probably has an greater effect on IgD and IgE as can be seen from the amount of samples that contain these two isotypes in @fig-isocount which shows that 23 out of the 31 samples contain IgD and not a single sample registered IgE. 

IgD is naturally concentrated around the peripheral areas of the circulatory system. It would therefore make sense that samples taken from other places would contain a much lower level of IgD. The lower levels will skew the isotype balance away from the IgD hidding anything that may be gained from knowing the true value. 

IgE on the other hand is completely missing. The naturally low levels of IgE combined with it being concentrated on mast cells is probably the main culprit here. When combined with the fact that people living in countries with good sanitation, like Great Britain in the study, generally are less exposed to the parasites that trigger the production of IgE. It creates a scenario where people have low levels of IgE that get snatched up by the mast cells. So for any information from IgE is completely lost.

This may be mitigated by taking serum samples from less intuitive places, and if it shows that those serum samples differ from the standard serum samples. This thought can be extended to IgA as most of that is secreted, maybe the comparison between the IgA subtype levels in certain secretions could bare more information for analysis, although considering that IgA is closer to a preventative subtype this feels redundant. What could be more interesting is the usage of alternative serum sampeling areas fro different things, it might not only be antibodies that are non-equally distributed throughout the body.

# Conclusion
This study attmpted to use open source data from past experiments to show that there was a relationship between disease and antibody isotype fingerprint. It uses data from the PRIDE repository in order to test if there is any visible statistical difference in the isotype distribution when afflicted with monkeypox, covid, or not afflicted at all. It would appear that the isotype fingerprint of a person changes while they have an affliction, it would also appear that it is based on the vector type or attact pattern rather than varying from individual disease to disease. There is not enough evidence to prove it definitely in this data.

# Future Perspectives
Future experiments could verify the finding,

and attempt to expand on it for other disease categories as well as see if there are more variation to be found than simply the identity of the vector. Another area that definately requires future work done, would be in fleshing out the data parameters on PRIDE, this would make the data there actually useful for future studies and reviews, instead of just creating the illusion of usefulness. 


# Data 
The source code for this project can be found on github at https://github.com/Trenchcoat-capybara/Antibody-fingerprints.git. This is a pdf rendering of the quarto document main.qmd which can be found in the root of the project.



# Disclosure
LLMs were used to find articles on topics, mainly claude was made to provide a list of scientific articles on a topic. They were also extensively used for debugging the code and constructing the figures designed in latex. Finally ChatGTP was used to proofread the report, correcting grammar, spelling, and formulation.


# Bibliography


